### PR TITLE
Updated Lightbend Banner

### PR DESCRIPTION
**Pull request by rasummer**
Updated Lightbend Banner for the Lagom website, we are now ready to deploy:

lagom-website

### CODE REVIEW

**Comment by rasummer** [comment]
Forgot to tag you above: @ennru @patriknw

**Comment by ignasi35** [comment]
related to https://github.com/playframework/playframework.com/pull/374

**Comment by rasummer** [comment]
Will be adding direct links to images soon, will update the PR

**Comment by rasummer** [comment]
@ignasi35 I deleted my fork by mistake. I will resubmit a new PR.

**Pull request closed without merging**
