### PR TITLE
Reduces fontsize and pading for inline code

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Comment by TimMoore** [comment]
Would you mind adding some screenshots that demonstrate the difference?

**Comment by ignasi35** [comment]
The change only impacts inline code (not snippets). 

Before:
before


After:
after

**Comment by TimMoore** [comment]
Yeah, a definite improvement to my eyes

**Comment by TimMoore** [comment]
We should port this over to the development theme in `lagom/lagom`, too.

**Comment by TimMoore** [comment]
Merged to the development theme in https://github.com/lagom/lagom/pull/423

Thanks, @ignasi35!

**Pull request merged**
