### PR TITLE
Added security.txt

### PR DESCRIPTION
**Pull request by jroper**
See https://securitytxt.org/

### CODE REVIEW

**Comment by ignasi35** [comment]
Nice! 

TIL: securitytxt.org

**Comment by TimMoore** [comment]
I think this didn't work. GitHub shows this as merged 16 hours ago (from when I type this) and the latest update to `master` 13 hours ago (https://github.com/lagom/lagom.github.io/commit/c6ac49ba5b44b847b9afe1bb3429856d93ecc423), but https://github.com/lagom/lagom.github.io/tree/master/.well-known doesn't exist.

I'm guessing that either the deployment script or something in the build for this repo excludes hidden directories (with a leading dot in the name).

**Comment by TimMoore** [comment]
It's because the default file filter in sbt is `HiddenFileFilter`. I'll fix.

**Comment by TimMoore** [comment]
#154

**Comment by TimMoore** [comment]
https://www.lagomframework.com/.well-known/security.txt still returns 404 even with #154 deployed

**Comment by TimMoore** [comment]
This line in the deploy script will also skip dot files https://github.com/lightbend/vegemite/blob/master/deploy/lagomNightlyDeployDocs#L87

**Comment by TimMoore** [comment]
Updated in https://github.com/lightbend/vegemite/pull/5

**Comment by TimMoore** [comment]
😖 https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Pull request merged**
