### PR TITLE
Remove Community Content and Videos

### PR DESCRIPTION
**Pull request by ignasi35**
This section was experimental. It proved a bit hard to maintain and keep up to date.

### CODE REVIEW

**Comment by ignasi35** [comment]
> It seems like a shame to remove links to helpful content, even if it's a little bit old. I would imagine that a lot of it would still be mostly relevant.

Let's keep the discussion open for a few days...

**Comment by ignasi35** [comment]
> Let's keep the discussion open for a few days...

It's been a few days. Ant other opinion on the subject? @TimMoore @marcospereira ?

**Comment by TimMoore** [comment]
I think it's good to have an area for community content. What makes it hard to maintain? Ideally, members of the community would be sending pull requests with links to their own material. Maybe it would be simpler to have the list of links directly in the HTML source rather than in Scala code?

**Comment by ignasi35** [comment]
Happy to be proven wrong #217

**Pull request closed without merging**
