### PR TITLE
Release 1.6.3

### PR DESCRIPTION
**Pull request by ihostage**

### CODE REVIEW

**Comment by renatocaval** [comment]
closing and reopening to verify that Mergify will update the checks

**Comment by renatocaval** [comment]
We are good, I can approve it without getting mergify to merge too soon. 

CleanShot 2020-07-22 at 22 43 28@2x

**Comment by ihostage** [comment]
@renatocaval Now we can remove `block-merge` label

**Comment by renatocaval** [comment]
Thanks @ihostage!

**Pull request merged**
